# Generated by Django 4.1.5 on 2023-02-10 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poster', models.ImageField(upload_to='posters/')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('about', models.TextField()),
            ],
            options={
                'verbose_name': 'Actor',
            },
        ),
        migrations.CreateModel(
            name='FilmModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poster', models.ImageField(upload_to='posters/')),
                ('video', models.FileField(upload_to='films/')),
                ('views_number', models.IntegerField(default=0)),
                ('name', models.CharField(help_text='zehmet olmasa simbol daxil edin', max_length=256)),
                ('rating', models.FloatField(default=0)),
                ('pub_date', models.DateField()),
                ('about', models.TextField()),
                ('actors', models.ManyToManyField(related_name='films', to='film.actormodel')),
            ],
            options={
                'verbose_name': 'Film',
            },
        ),
    ]
