# Generated by Django 4.1.5 on 2023-02-27 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0003_commentmodel_delete_commentmoodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentmodel',
            options={'ordering': ('-id',), 'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('film', models.ManyToManyField(related_name='film_category', to='film.filmmodel')),
            ],
            options={
                'verbose_name': 'Category',
            },
        ),
    ]
