# Generated by Django 4.1.5 on 2023-02-27 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0004_alter_commentmodel_options_categorymodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorymodel',
            name='film',
        ),
        migrations.AddField(
            model_name='categorymodel',
            name='films',
            field=models.ManyToManyField(related_name='film_categories', to='film.filmmodel'),
        ),
    ]
